// <auto-generated />
using Mango.Services.ProductAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Mango.Services.ProductAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Mango.Services.ProductAPI.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("InCart")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Src")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 7,
                            Description = "Kiwi Kiwi Kiwi Kiwi.",
                            InCart = false,
                            Name = "Kiwi",
                            Price = 50000,
                            Quantity = 0,
                            Src = "https://images.pexels.com/photos/51312/kiwi-fruit-vitamins-healthy-eating-51312.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500"
                        },
                        new
                        {
                            ProductId = 1,
                            Description = "Watermelon Watermelon Watermelon Watermelon.",
                            InCart = false,
                            Name = "Watermelon",
                            Price = 65000,
                            Quantity = 0,
                            Src = "https://images.pexels.com/photos/1313267/pexels-photo-1313267.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500"
                        },
                        new
                        {
                            ProductId = 2,
                            Description = "Cherry Cherry Cherry .",
                            InCart = false,
                            Name = "Cherry",
                            Price = 100000,
                            Quantity = 0,
                            Src = "https://images.pexels.com/photos/109274/pexels-photo-109274.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500"
                        },
                        new
                        {
                            ProductId = 3,
                            Description = "Avacado Avacado Avacado Avacado.",
                            InCart = false,
                            Name = "Avacado",
                            Price = 120000,
                            Quantity = 0,
                            Src = "https://images.pexels.com/photos/557659/pexels-photo-557659.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500"
                        },
                        new
                        {
                            ProductId = 4,
                            Description = "Apple Apple Apple Apple.",
                            InCart = false,
                            Name = "Apple",
                            Price = 80000,
                            Quantity = 0,
                            Src = "https://images.pexels.com/photos/102104/pexels-photo-102104.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500"
                        },
                        new
                        {
                            ProductId = 5,
                            Description = "Strawberry Strawberry Strawberry Strawberry.",
                            InCart = false,
                            Name = "Strawberry",
                            Price = 50000,
                            Quantity = 0,
                            Src = "https://images.pexels.com/photos/934066/pexels-photo-934066.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500"
                        },
                        new
                        {
                            ProductId = 6,
                            Description = "Orange Orange Orange Orange.",
                            InCart = false,
                            Name = "Orange",
                            Price = 50000,
                            Quantity = 0,
                            Src = "https://images.pexels.com/photos/42059/citrus-diet-food-fresh-42059.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
